#!/bin/bash

CONTAINER=" "

while getopts ":c:" opt; do
  case $opt in
    c) CONTAINER="-name $OPTARG"
    ;;
  esac
done

erl +t 100000000 $CONTAINER -pa ./ebin/ ./agents ./agents/erlang ./include -run ejason start "$@"
